Dynamic image import
foxfriends/root pull request #50
Opened 2021-02-09 21:12 UTC by agdust

I've grouped all images and uploaded some new quality ones

2021-02-09 21:30 UTC, foxfriends requested changes
Just this one small thing. 

It's too bad we cannot use a function for the CSS image references, maybe those can go in a file of CSS variables though? That can be for next time if ever though.

2021-02-09 21:30 UTC, foxfriends commented on app/util/image.js
> +}
I would prefer this to be two functions, one for front and one for back. The meaning of the final boolean is unclear when called.

2021-02-10 08:07 UTC, agdust commented
> we cannot use a function for the CSS image references

We still can define custom-properties in component itself like `style={--image-we-need: url(${getImagePath()})}`

I think this way covers any problem with css images, because there will be few of them (most of images will be defined in the style attribute). And if we'll try to pass _all_ images to css, we'll get this huge files that we've got rid just now

2021-02-10 14:38 UTC, foxfriends commented
> > we cannot use a function for the CSS image references
> 
> We still can define custom-properties in component itself like `style={--image-we-need: url(${getImagePath()})}`
> 
> I think this way covers any problem with css images, because there will be few of them (most of images will be defined in the style attribute). And if we'll try to pass _all_ images to css, we'll get this huge files that we've got rid just now

Let's just leave this alone for now, there's not too many of them. I think that could be done just using `background-image` in the style property most of the time, not needing the custom one.

2021-02-10 16:22 UTC, foxfriends approved these changes

2021-02-10 16:23 UTC, foxfriends commented
Thanks!

2021-02-10 16:23 UTC, merged